import {
  Bell,
  ChevronLeft,
  ChevronRight,
  CircleHelp,
  Copy,
  Dna,
  GitBranch,
  GitFork,
  GitMerge,
  Globe,
  Heart,
  History,
  KeyRound,
  LayoutGrid,
  Lock,
  LogOut,
  Maximize2,
  Menu,
  Network,
  Pencil,
  Plus,
  Search,
  Unlock,
  UserPlus,
  Users,
  X,
  ZoomIn,
  ZoomOut,
  type LucideProps,
} from 'lucide-react'

const ICONS = {
  copy: Copy,
  bell: Bell,
  key: KeyRound,
  logout: LogOut,
  plus: Plus,
  close: X,
  back: ChevronLeft,
  next: ChevronRight,
  people: Users,
  invite: UserPlus,
  edit: Pencil,
  lock: Lock,
  unlock: Unlock,
  globe: Globe,
  history: History,
  branch: GitBranch,
  lineage: GitFork,
  union: GitMerge,
  network: Network,
  search: Search,
  menu: Menu,
  help: CircleHelp,
  map: LayoutGrid,
  zoomIn: ZoomIn,
  zoomOut: ZoomOut,
  fit: Maximize2,
  heart: Heart,
  dna: Dna,
} as const

export type IconName = keyof typeof ICONS

export function Icon({ name, ...props }: LucideProps & Readonly<{ name: IconName }>) {
  const LucideIcon = ICONS[name]
  return <LucideIcon size={16} strokeWidth={2} aria-hidden="true" focusable="false" {...props} />
}
